base_config: ./base.yaml
task_cls: tasks.tts.fastspeech.FastSpeechTask
dataset_cls: tasks.tts.dataset_utils.FastSpeechDataset
model_cls: models.tts.fastspeech.FastSpeech

# model
hidden_size: 256

# fft enc/dec
encoder_layers: 4
encoder_ffn_kernel_size: 9
decoder_layers: 4
decoder_ffn_kernel_size: 9
num_heads: 2
ffn_act: relu
ffn_hidden_size: 1024

# duration
dur_predictor_kernel: 3
dur_predictor_layers: 2
predictor_kernel: 5
predictor_layers: 5
predictor_dropout: 0.5

# mel
mel_losses: l1 # l1|l2|gdl|ssim or l1:0.5|ssim:0.5

# loss lambda
lambda_dur: 1.0

# train and eval
warmup_updates: 4000
max_updates: 160000
max_sentences: 48
